version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: php-madlibs-exercise
    volumes:
      - ".:/application"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=php-madlibs-exercise"
      LOG_LEVEL: 'debug'
